apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: notes-app
  labels:
    app: notes-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: notes-app

  template:
    metadata:
      labels:
        app: notes-app

    spec:
      containers:
        - name: notes-app
          image: sudarshan0907/notes-app-k8s:__IMAGE_TAG__
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /api/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          envFrom:
            - secretRef:
                name: mysql-secret

          env:
            - name: MYSQL_HOST
              value: mysql

            - name: MYSQL_PORT
              value: "3306"

            - name: DJANGO_ALLOWED_HOSTS
              value: "*"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
