apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: notes-app
  labels:
    app: notes-app

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: notes-app

  template:
    metadata:
      labels:
        app: notes-app

    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001
      initContainers:
        - name: migrate
          image: sudarshan0907/notes-app-k8s:latest
          imagePullPolicy: Never
          command:
            - sh
            - -c
            - python manage.py migrate --noinput
          envFrom:
            - configMapRef:
                name: notes-app-config
            - secretRef:
                name: mysql-secret
      containers:
        - name: notes-app
          image: sudarshan0907/notes-app-k8s:latest
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 8000

          envFrom:
            - configMapRef:
                name: notes-app-config
            - secretRef:
                name: mysql-secret

          command:
            - gunicorn
            - --bind
            - 0.0.0.0:8000
            - --workers
            - "3"
            - --timeout
            - "60"
            - --access-logfile
            - "-"
            - --error-logfile
            - "-"
            - notesapp.wsgi:application

          readinessProbe:
            httpGet:
              path: /api/readyz/
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/healthz/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
